server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///shop
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 121122
  rabbitmq:
    host: 192.168.111.128
    username: admin
    password: admin
    port: 5672
    virtual-host: /admin
  redis:
    host: 192.168.111.128
dubbo:
  application:
    name: goods_service
  registry:
    address: zookeeper://192.168.111.128:2181
  protocol:
    port: -1
  consumer:
    check: false
mybatis-plus:
  mapper-locations: classpath:com/qf/dao/mapper/*.xml