server:
  port: 8080
spring:
  thymeleaf:
    cache: false
dubbo:
  application:
    name: shop_back
  registry:
    address: zookeeper://192.168.111.128:2181
  consumer:
    check: false
fdfs:
  tracker-list: 192.168.111.128:22122
  thumb-image:
    width: 100
    height: 100
  pool:
    jmx-enabled: false
  servicepath: http://192.168.111.128/